version: '3.3'
services:
  portainer:
    image: portainer/portainer
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /opt/docker/portainer:/data
    command: --admin-password "${PASSWORD_HASH}"
    ports:
        - "47501:9000"
